export const PAGE_SIZE = 10;

export const ASK_QUESTION_REPUTATION = 5;
export const ANSWER_QUESTION_REPUTATION = 10;
export const UPVOTE_QUESTION_REPUTATION = 5;
export const DOWNVOTE_QUESTION_REPUTATION = -2;
export const UPVOTE_ANSWER_REPUTATION = 10;
export const DOWNVOTE_ANSWER_REPUTATION = -2;
